---
abstract: 'automatically sets the bugtracker URL'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Bugtracker
provides:
  Dist::Zilla::Plugin::Bugtracker:
    file: lib/Dist/Zilla/Plugin/Bugtracker.pm
    version: 1.100701
requires:
  Dist::Zilla::Role::MetaProvider: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::More: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Bugtracker
  repository: http://github.com/hanekomu/Dist-Zilla-Plugin-Bugtracker
version: 1.100701
